version: "3.3"

services:
  lb:
    image: nginx:latest
    volumes:
     - ./lb:/etc/nginx/
    networks:
      app_net:
        ipv4_address: 10.10.10.5
  node1:
    image: nginx
    volumes:
     - ./node1:/usr/share/nginx/html/
    networks:
      app_net:
        ipv4_address: 10.10.10.7
  node2:
    image: nginx
    volumes:
     - ./node2:/usr/share/nginx/html/
    networks:
      app_net:
        ipv4_address: 10.10.10.8
  node3:
    image: nginx
    volumes:
     - ./node3:/usr/share/nginx/html/
    networks:
      app_net:
        ipv4_address: 10.10.10.9
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
