version: "3.3"

services:
  lb:
    image: nginx:latest
    container_name: load-balancer
    volumes:
     - ./lb/nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 8888:80 #Binding host port 8888 to container port 80
    networks:
      app_net:
        ipv4_address: 10.10.10.5
  node1:
    image: nginx:latest
    container_name: node1
    volumes:
     - ./node1:/usr/share/nginx/html/
    depends_on:
     - lb
    networks:
      app_net:
        ipv4_address: 10.10.10.7
  node2:
    image: nginx:latest
    container_name: node2
    volumes:
     - ./node2:/usr/share/nginx/html/
    depends_on:
     - lb
    networks:
      app_net:
        ipv4_address: 10.10.10.8
  node3:
    image: nginx:latest
    container_name: node3
    volumes:
     - ./node3:/usr/share/nginx/html/
    depends_on:
     - lb
    networks:
      app_net:
        ipv4_address: 10.10.10.9
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
